import {
  ArrowUp,
  BarChart3,
  ChevronDown,
  ChevronUp,
  Database,
  Filter,
  Github,
  Lock,
  Moon,
  Palette,
  Rocket,
  Search,
  Sun,
  TestTube,
  Zap,
} from "lucide-react";

export const Icons = {
  sun: Sun,
  moon: Moon,
  github: Github,
  search: Search,
  filter: Filter,
  performance: Zap,
  uiux: Palette,
  database: Database,
  security: Lock,
  devops: Rocket,
  testing: TestTube,
  analytics: BarChart3,
  arrowUp: ArrowUp,
  chevronDown: ChevronDown,
  chevronUp: ChevronUp,
};
